# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
COPY . /app
RUN npm run-script build
COPY ./src/.env /app/dist
EXPOSE 8010
CMD ["node", "/app/dist/index.js"]
